In [1]:
# Pandas is used for data manipulation
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate
from xgboost import XGBClassifier

In [2]:
features = pd.read_csv('dataset/apimdsComplete.csv')
features.head(5)

,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10,Column11,Column12,...,Column101,Column102,Column103,Column104,Column105,Column106,Column107,Column108,Column109,malware
0,444,549,592,145,144,507,960,583,750,116,...,855,854,866,899,270,896,742,894,887,1
1,444,549,592,145,144,507,960,583,750,116,...,855,854,866,899,270,896,742,894,887,1
2,444,549,592,145,144,507,960,583,750,116,...,855,854,866,899,270,896,742,894,887,1
3,444,549,592,145,144,507,960,583,750,116,...,855,854,866,899,270,896,742,894,887,1
4,444,549,592,145,144,507,960,583,750,116,...,855,854,866,899,270,896,742,894,887,1

In [3]:
print('The shape of our features is:', features.shape)
features.dtypes

The shape of our features is: (21789, 108)

Column3      int64
Column4      int64
Column5      int64
Column6      int64
Column7      int64
             ...
Column106    int64
Column107    int64
Column108    int64
Column109    int64
malware      int64
Length: 108, dtype: object

In [4]:
# Descriptive statistics for each column
features.describe()

,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10,Column11,Column12,...,Column101,Column102,Column103,Column104,Column105,Column106,Column107,Column108,Column109,malware
count,21789.000000,21789.000000,21789.000000,21789.000000,21789.000000,21789.000000,21789.000000,21789.000000,21789.000000,21789.000000,...,21789.000000,21789.000000,21789.000000,21789.000000,21789.000000,21789.000000,21789.000000,21789.000000,21789.000000,21789.000000
mean,537.920878,475.402267,494.713066,391.770113,445.504016,491.851898,601.193033,493.182386,406.218734,435.775391,...,524.188581,525.986323,484.819771,468.011290,490.888751,464.588783,498.965808,508.059663,474.685346,0.986369
std,202.201985,168.069046,220.834424,204.527064,240.865104,184.651624,273.864274,206.417058,228.683954,247.284701,...,223.750346,226.178239,247.199112,248.310067,236.104005,252.731983,228.202039,239.055265,230.967373,0.115955
min,30.000000,34.000000,34.000000,4.000000,4.000000,18.000000,5.000000,11.000000,5.000000,28.000000,...,3.000000,18.000000,4.000000,10.000000,4.000000,20.000000,4.000000,5.000000,17.000000,0.000000
25%,444.000000,397.000000,396.000000,304.000000,304.000000,397.000000,397.000000,396.000000,145.000000,144.000000,...,395.000000,396.000000,305.000000,270.000000,304.000000,322.000000,396.000000,397.000000,304.000000,1.000000
50%,486.000000,485.000000,435.000000,396.000000,419.000000,514.000000,519.000000,508.000000,419.000000,437.000000,...,507.000000,551.000000,486.000000,423.000000,483.000000,447.000000,473.000000,486.000000,446.000000,1.000000
75%,592.000000,486.000000,582.000000,507.000000,517.000000,592.000000,956.000000,595.000000,559.000000,592.000000,...,646.000000,716.000000,595.000000,592.000000,602.000000,604.000000,601.000000,621.000000,595.000000,1.000000
max,962.000000,962.000000,962.000000,962.000000,962.000000,962.000000,962.000000,962.000000,962.000000,962.000000,...,968.000000,967.000000,968.000000,968.000000,968.000000,968.000000,968.000000,967.000000,968.000000,1.000000

In [5]:
# Labels are the values we want to predict
labels = features['malware']

# Remove the labels from the features
# axis 1 refers to the columns
features = features.drop('malware', axis = 1)


# Saving feature names for later use
feature_list = list(features.columns)

# Convert to numpy array
#features = np.array(features)

In [6]:
# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, random_state = 42)

In [7]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)

Training Features Shape: (16341, 107)
Training Labels Shape: (16341,)
Testing Features Shape: (5448, 107)
Testing Labels Shape: (5448,)

In [8]:
# Instantiate model with 1000 decision trees
xgb = XGBClassifier(n_jobs=-1, max_depth=6, use_label_encoder=False, learning_rate=0.3)

In [13]:
scoring = ['precision_macro', 'recall_macro', 'f1_macro', 'roc_auc']
scores = cross_validate(xgb, train_features, train_labels, cv=10, scoring=scoring)

[17:17:00] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[17:17:01] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[17:17:02] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[17:17:02] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[17:17:03] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[17:17:04] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[17:17:04] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[17:17:05] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[17:17:06] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[17:17:07] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

In [14]:
sorted(scores.keys())

['fit_time',
 'score_time',
 'test_f1_macro',
 'test_precision_macro',
 'test_recall_macro',
 'test_roc_auc']

In [15]:
scores['test_roc_auc']

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
print("%0.4f accuracy" % (scores['test_precision_macro'].mean()))
print("%0.4f recall" % (scores['test_recall_macro'].mean()))
print("%0.4f f1 score" % (scores['test_f1_macro'].mean()))
print("%0.4f auc roc" % (scores['test_roc_auc'].mean()))
print("-"*25)
print("%0.5f training time" % (scores['fit_time'].sum()))
print("%0.5f predition time" % (scores['score_time'].mean()))

1.0000 accuracy
1.0000 recall
1.0000 f1 score
1.0000 auc roc
-------------------------
7.05980 training time
0.01446 predition time