In [1]:
# Pandas is used for data manipulation
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate
from catboost import CatBoostClassifier

In [2]:
features = pd.read_csv('dataset/apimdsCat.csv')
features.head(5)

,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10,Column11,Column12,...,Column_99,Column_100,Column_101,Column_102,Column_103,Column_104,Column_105,Column_106,Column_107,malware
0,468,577,620,158,157,533,961,611,740,129,...,61,58,304,306,89,308,277,319,312,1
1,468,577,620,158,157,533,961,611,740,129,...,61,58,303,289,303,309,88,321,277,1
2,468,577,620,158,157,533,961,611,740,129,...,236,61,62,291,319,85,319,275,316,1
3,468,577,620,158,157,533,961,611,740,129,...,61,58,304,306,89,308,277,319,312,1
4,468,577,620,158,157,533,961,611,740,129,...,61,58,304,306,89,308,277,319,312,1

In [4]:
print('The shape of our features is:', features.shape)
features.dtypes

The shape of our features is: (21492, 213)

Column3       int64
Column4       int64
Column5       int64
Column6       int64
Column7       int64
              ...
Column_104    int64
Column_105    int64
Column_106    int64
Column_107    int64
malware       int64
Length: 213, dtype: object

In [5]:
# Descriptive statistics for each column
features.describe()

,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10,Column11,Column12,...,Column_99,Column_100,Column_101,Column_102,Column_103,Column_104,Column_105,Column_106,Column_107,malware
count,21492.000000,21492.000000,21492.000000,21492.000000,21492.000000,21492.000000,21492.000000,21492.000000,21492.000000,21492.000000,...,21492.000000,21492.000000,21492.000000,21492.000000,21492.000000,21492.000000,21492.000000,21492.000000,21492.000000,21492.0
mean,555.635260,494.352969,510.725572,405.950447,459.497255,510.247208,614.240043,508.017448,420.552252,449.548576,...,183.259166,160.802345,190.366741,181.179695,174.387260,161.952587,179.486227,166.916481,185.526289,1.0
std,196.644243,166.141947,217.839455,204.224938,238.538748,184.712489,268.149147,203.561463,228.294666,245.967649,...,93.250625,93.843481,84.670552,82.711830,93.912652,91.564528,90.982811,97.753710,84.164895,0.0
min,32.000000,36.000000,36.000000,2.000000,2.000000,18.000000,3.000000,11.000000,3.000000,30.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0
25%,468.000000,417.000000,416.000000,266.000000,320.000000,417.000000,417.000000,414.000000,158.000000,157.000000,...,105.000000,86.000000,135.000000,126.000000,97.000000,85.000000,98.000000,103.000000,146.000000,1.0
50%,512.000000,511.000000,445.000000,416.000000,440.000000,534.000000,545.000000,534.000000,440.000000,461.000000,...,187.000000,161.000000,185.000000,201.000000,177.000000,141.000000,182.000000,162.000000,181.000000,1.0
75%,620.000000,512.000000,610.000000,533.000000,543.000000,620.000000,957.000000,623.000000,567.000000,620.000000,...,250.000000,227.000000,245.000000,245.000000,230.000000,223.000000,241.000000,240.000000,236.000000,1.0
max,963.000000,963.000000,963.000000,963.000000,963.000000,963.000000,963.000000,963.000000,963.000000,963.000000,...,353.000000,343.000000,355.000000,336.000000,357.000000,345.000000,352.000000,356.000000,352.000000,1.0

In [3]:
features.dropna(inplace=True)

In [6]:
# Labels are the values we want to predict
labels = features['malware']

# Remove the labels from the features
# axis 1 refers to the columns
features = features.drop('malware', axis = 1)


# Saving feature names for later use
feature_list = list(features.columns)

# Convert to numpy array
#features = np.array(features)

In [7]:
# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, random_state = 42)

In [8]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)

Training Features Shape: (16119, 212)
Training Labels Shape: (16119,)
Testing Features Shape: (5373, 212)
Testing Labels Shape: (5373,)

In [9]:
# Instantiate model with 1000 decision trees
catboost = CatBoostClassifier()

In [13]:
scoring = ['precision_macro', 'recall_macro', 'f1_macro', 'roc_auc']
scores = cross_validate(catboost, train_features, train_labels, cv=10, scoring=scoring)

/home/alessio/.local/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning:
10 fits failed out of a total of 10.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "_catboost.pyx", line 2175, in _catboost.get_float_feature
  File "_catboost.pyx", line 1126, in _catboost._FloatOrNan
  File "_catboost.pyx", line 949, in _catboost._FloatOrNanFromString
TypeError: Cannot convert 'b'GetModuleFileNameW'' to float

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alessio/.local/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alessio/.local/lib/python3.10/site-packages/catboost/core.py", line 4768, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
  File "/home/alessio/.local/lib/python3.10/site-packages/catboost/core.py", line 2073, in _fit
    train_params = self._prepare_train_params(
  File "/home/alessio/.local/lib/python3.10/site-packages/catboost/core.py", line 1959, in _prepare_train_params
    train_pool = _build_train_pool(X, y, cat_features, text_features, embedding_features, pairs,
  File "/home/alessio/.local/lib/python3.10/site-packages/catboost/core.py", line 1241, in _build_train_pool
    train_pool = Pool(X, y, cat_features=cat_features, text_features=text_features, embedding_features=embedding_features, pairs=pairs, weight=sample_weight, group_id=group_id,
  File "/home/alessio/.local/lib/python3.10/site-packages/catboost/core.py", line 645, in __init__
    self._init(data, label, cat_features, text_features, embedding_features, pairs, weight,
  File "/home/alessio/.local/lib/python3.10/site-packages/catboost/core.py", line 1222, in _init
    self._init_pool(data, label, cat_features, text_features, embedding_features, pairs, weight,
  File "_catboost.pyx", line 3763, in _catboost._PoolBase._init_pool
  File "_catboost.pyx", line 3812, in _catboost._PoolBase._init_pool
  File "_catboost.pyx", line 3646, in _catboost._PoolBase._init_features_order_layout_pool
  File "_catboost.pyx", line 2672, in _catboost._set_features_order_data_pd_data_frame
  File "_catboost.pyx", line 2216, in _catboost.create_num_factor_data
  File "_catboost.pyx", line 2177, in _catboost.get_float_feature
_catboost.CatBoostError: Bad value for num_feature[non_default_doc_idx=0,feature_idx=57]="GetModuleFileNameW": Cannot convert 'b'GetModuleFileNameW'' to float

--------------------------------------------------------------------------------
9 fits failed with the following error:
Traceback (most recent call last):
  File "_catboost.pyx", line 2175, in _catboost.get_float_feature
  File "_catboost.pyx", line 1126, in _catboost._FloatOrNan
  File "_catboost.pyx", line 949, in _catboost._FloatOrNanFromString
TypeError: Cannot convert 'b'CallNextHookEx'' to float

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alessio/.local/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/alessio/.local/lib/python3.10/site-packages/catboost/core.py", line 4768, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
  File "/home/alessio/.local/lib/python3.10/site-packages/catboost/core.py", line 2073, in _fit
    train_params = self._prepare_train_params(
  File "/home/alessio/.local/lib/python3.10/site-packages/catboost/core.py", line 1959, in _prepare_train_params
    train_pool = _build_train_pool(X, y, cat_features, text_features, embedding_features, pairs,
  File "/home/alessio/.local/lib/python3.10/site-packages/catboost/core.py", line 1241, in _build_train_pool
    train_pool = Pool(X, y, cat_features=cat_features, text_features=text_features, embedding_features=embedding_features, pairs=pairs, weight=sample_weight, group_id=group_id,
  File "/home/alessio/.local/lib/python3.10/site-packages/catboost/core.py", line 645, in __init__
    self._init(data, label, cat_features, text_features, embedding_features, pairs, weight,
  File "/home/alessio/.local/lib/python3.10/site-packages/catboost/core.py", line 1222, in _init
    self._init_pool(data, label, cat_features, text_features, embedding_features, pairs, weight,
  File "_catboost.pyx", line 3763, in _catboost._PoolBase._init_pool
  File "_catboost.pyx", line 3812, in _catboost._PoolBase._init_pool
  File "_catboost.pyx", line 3646, in _catboost._PoolBase._init_features_order_layout_pool
  File "_catboost.pyx", line 2672, in _catboost._set_features_order_data_pd_data_frame
  File "_catboost.pyx", line 2216, in _catboost.create_num_factor_data
  File "_catboost.pyx", line 2177, in _catboost.get_float_feature
_catboost.CatBoostError: Bad value for num_feature[non_default_doc_idx=0,feature_idx=57]="CallNextHookEx": Cannot convert 'b'CallNextHookEx'' to float

  warnings.warn(some_fits_failed_message, FitFailedWarning)

In [10]:
sorted(scores.keys())

['fit_time',
 'score_time',
 'test_f1_macro',
 'test_precision_macro',
 'test_recall_macro',
 'test_roc_auc']

In [20]:
print("%0.4f accuracy" % (scores['test_precision_macro'].mean()))
print("%0.4f recall" % (scores['test_recall_macro'].mean()))
print("%0.4f f1 score" % (scores['test_f1_macro'].mean()))
print("%0.4f auc roc" % (scores['test_roc_auc'].mean()))
print("-"*25)
print("%0.5f training time" % (scores['fit_time'].sum()))
print("%0.5f predition time" % (scores['score_time'].mean()))

0.9551 accuracy
0.8122 recall
0.8694 f1 score
0.9773 auc roc
-------------------------
87.62187 training time
0.01686 predition time